version: '3.8'
services:
  coursesmanagmentmicroservices.api:
    image: coursesmanagmentmicroservicesapi
    build:
      context: .
      dockerfile: CoursesManagmentMicroservices.API/Dockerfile
    ports:
      - "7000:8080"
    environment:
      - MSSQL_SERVER=e-learning-db
      - MSSQL_DB=Eductional-Courses-DB
      - MSSQL_PASSWORD=AhmedAteya12348@#
      - UserMicroserviceName=usermicroservices
      - userMicroservicePort=8080
    networks:
      - eductional
    depends_on:
      - usermicroservices

  usermicroservices:
    image: ahmedateya/userservices:latest
    ports:
      - "8080:8080" 
    environment:
      - SERVER_NAME=e-learning-db
      - DATABASE_NAME=Eductional-Users-DB
      - USER_SQLSERVER=sa
      - PASSWORD_SQLSERVER=AhmedAteya12348@#
      - ASPNETCORE_URLS=http://+:8080 
    networks:
      - eductional
    depends_on:
      - e-learning-db

  e-learning-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AhmedAteya12348@#
    networks:
      - eductional
    volumes:
      - eductional_data:/var/opt/mssql

networks:
  eductional:
    driver: bridge

volumes:
  eductional_data:
    driver: local
