services:
  usersmicroserviceseductional.api:
    image: usersmicroserviceseductionalapi
    build:
      context: .
      dockerfile: UsersMicroservicesEductional.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_NAME=db
      - DATABASE_NAME=Eductional-Users-DB
      - USER_SQLSERVER=sa
      - PASSWORD_SQLSERVER=AhmedAteya12348@#
    depends_on:
        - db
    networks:
      - eductional
  db:
   image: mcr.microsoft.com/mssql/server:2022-latest
   ports:
      - "1433:1433"
   environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AhmedAteya12348@#
   networks:
      - eductional
networks:
  eductional:
    driver: bridge
