services:
  usersmicroserviceseductional.api:
    image: usersmicroserviceseductionalapi
    build:
      context: .
      dockerfile: UsersMicroservicesEductional.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_NAME=db
      - DATABASE_NAME=Eductional-Users-DB
      - USER_SQLSERVER=sa
      - PASSWORD_SQLSERVER=AhmedAteya12348@#
    depends_on:
      - db
    networks:
      - eductional

  coursemicroservices:
    image: ahmedateya/courses-managment:latest
    ports:
      - "7000:8080"
    environment:
      - MSSQL_SERVER=db
      - MSSQL_DB=Eductional-Courses-DB
      - MSSQL_PASSWORD=AhmedAteya12348@#
    networks:
      - eductional
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AhmedAteya12348@#
    networks:
      - eductional
    volumes:
      - sqlserver_data:/var/opt/mssql

networks:
  eductional:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
